/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'
import { Route as SessionSessionIdResultRouteImport } from './routes/session_.$sessionId.result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdResultRoute = SessionSessionIdResultRouteImport.update({
  id: '/session_/$sessionId/result',
  path: '/session/$sessionId/result',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/$sessionId/result': typeof SessionSessionIdResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/$sessionId/result': typeof SessionSessionIdResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session_/$sessionId/result': typeof SessionSessionIdResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/session/$sessionId' | '/session/$sessionId/result'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/session/$sessionId' | '/session/$sessionId/result'
  id: '__root__' | '/' | '/session/$sessionId' | '/session_/$sessionId/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
  SessionSessionIdResultRoute: typeof SessionSessionIdResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session_/$sessionId/result': {
      id: '/session_/$sessionId/result'
      path: '/session/$sessionId/result'
      fullPath: '/session/$sessionId/result'
      preLoaderRoute: typeof SessionSessionIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
  SessionSessionIdResultRoute: SessionSessionIdResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
